In [1]:
import numpy as np


In [2]:
#creating simple dimension array


In [4]:
a=np.array([1,34,5,77,8])

In [6]:
# another 1D array
b=np.array([44,77,1,88])

In [7]:
a


array([ 1, 34,  5, 77,  8])

In [8]:
b


array([44, 77,  1, 88])

In [13]:
# creating 2D array
x=np.array([[2,88],[33,8],[55,8],[33,9]])

In [14]:
x


array([[ 2, 88],
       [33,  8],
       [55,  8],
       [33,  9]])

In [15]:
x[0]


array([ 2, 88])

In [16]:
x[[0]]

array([[ 2, 88]])

In [17]:
x[0,1]


88

In [18]:
x[0][1] #first-row second- column

88

In [19]:
x[2,0]

55

In [20]:
x[0:2]

array([[ 2, 88],
       [33,  8]])

In [23]:
x[0:1][0:3]

array([[ 2, 88]])

In [25]:
x+3


array([[ 5, 91],
       [36, 11],
       [58, 11],
       [36, 12]])

In [26]:
x*2


array([[  4, 176],
       [ 66,  16],
       [110,  16],
       [ 66,  18]])

In [27]:
x/4

array([[ 0.5 , 22.  ],
       [ 8.25,  2.  ],
       [13.75,  2.  ],
       [ 8.25,  2.25]])

In [28]:


x**2


array([[   4, 7744],
       [1089,   64],
       [3025,   64],
       [1089,   81]])

In [29]:
x


array([[ 2, 88],
       [33,  8],
       [55,  8],
       [33,  9]])

In [30]:
#to check dimension

In [32]:
x.shape


(4, 2)

In [36]:
y=x.reshape(2,4)


In [37]:
y[0]

array([ 2, 88, 33,  8])

In [38]:
#if only columns

In [40]:
y[0:,1]

array([88,  8])

In [43]:
y[:,1]


array([88,  8])

In [44]:
y[:,1:]

array([[88, 33,  8],
       [ 8, 33,  9]])

In [45]:
y[0:,3:]

array([[8],
       [9]])

In [46]:
y(0,2)

TypeError: 'numpy.ndarray' object is not callable

In [47]:
y[1,2]

33

In [48]:
np.zeros((5,5))  #to create a matrix of zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:

np.ones((9,9))  #to create a matrix of ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [53]:
np.full((4,6),9) #to create a matrix of desired number n,here n=9

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [57]:
np.ones((4,4),dtype='int32')   #to create a matrix of desired data type


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [58]:
#mathops

In [59]:
x


array([[ 2, 88],
       [33,  8],
       [55,  8],
       [33,  9]])

In [60]:
x1=x*2

In [61]:
x1

array([[  4, 176],
       [ 66,  16],
       [110,  16],
       [ 66,  18]])

In [62]:
#to add we can use a function

In [63]:
np.add(x,x1)

array([[  6, 264],
       [ 99,  24],
       [165,  24],
       [ 99,  27]])